name: main action

on:
  push:
  schedule:
    - cron: "0 */24 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: add settings.json
        env:
          content: ${{ secrets.settings }}
        run: |
          echo "$content" > settings.json

      - name: run
        run: python main.py settings.json
