name: send msg to tg

on:
  schedule:
    - cron: "0 12 */1 * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: add settings.json
        env:
          content: ${{ secrets.settings }}
        run: |
          echo "$content" > settings.json

      - name: run
        env:
          sk: ${{ secrets.sk }}
          id: ${{ secrets.id}}
        run: |
          python main.py settings.json > out
          ddl=$(expr $(date -d "Dec 25 2021" +%j) - $(date +%j))
          curl -k -d chat_id="$id" -d "text=$(cat out)" https://api.telegram.org/bot$sk/sendMessage
          curl -k -d chat_id="$id" -d "text=还有$ddl天💀" https://api.telegram.org/bot$sk/sendMessage
